import guitar1 from "../assets/images/guitar-bass.jpg";
import guitar2 from "../assets/images/guitar-z300.jpg";
import guitar3 from "../assets/images/guitar-lx.jpg";
import guitar4 from "../assets/images/guitar-t300.jpg";
import guitar5 from "../assets/images/guitar-super.jpg";
import guitar6 from "../assets/images/guitar-plus.jpg";
import acustic from "../assets/images/acustic.jpg";
import electro from "../assets/images/electro.jpg";
import ukulele from "../assets/images/ukulele.jpg";

export const GuitarshopService = [
  {
    id: 1,
    image: guitar1,
    type: {
      name: "electro",
      value: "Электрогитара",
      image: electro,
    },
    raiting: 4,
    popularity: 15,
    name: "Честер Bass",
    price: 17500,
    countString: 7,
    setNumber: "SO757575",
  },
  {
    id: 2,
    image: guitar2,
    raiting: 5,
    type: {
      name: "electro",
      value: "Электрогитара",
      image: electro,
    },
    popularity: 9,
    name: "СURT Z300",
    price: 29500,
    countString: 7,
    setNumber: "TK129049",
  },
  {
    id: 3,
    image: guitar3,
    raiting: 4,
    type: {
      name: "ukulele",
      value: "Укулеле",
      image: ukulele,
    },
    popularity: 21,
    name: "Roman LX",
    price: 6800,
    countString: 4,
    setNumber: "RO111111",
  },
  {
    id: 4,
    image: guitar4,
    raiting: 4,
    type: {
      name: "electro",
      value: "Электрогитара",
      image: electro,
    },
    popularity: 15,
    name: "СURT T300",
    price: 30000,
    countString: 6,
    setNumber: "TK436457",
  },
  {
    id: 5,
    image: guitar5,
    raiting: 4,
    type: {
      name: "acustic",
      value: "Акустическая гитара",
      image: acustic,
    },
    popularity: 5,
    name: "Dania Super",
    price: 3500,
    countString: 7,
    setNumber: "DI192138",
  },
  {
    id: 6,
    image: guitar1,
    raiting: 4,
    type: {
      name: "electro",
      value: "Электрогитара",
      image: electro,
    },
    popularity: 17,
    name: "Честер WX",
    price: 15300,
    countString: 6,
    setNumber: "SO934345",
  },
  {
    id: 7,
    image: guitar3,
    raiting: 4.5,
    type: {
      name: "ukulele",
      value: "Укулеле",
      image: ukulele,
    },
    popularity: 5,
    name: "Dania VX",
    price: 2200,
    countString: 4,
    setNumber: "DI082347",
  },
  {
    id: 8,
    image: guitar6,
    raiting: 4,
    type: {
      name: "electro",
      value: "Электрогитара",
      image: electro,
    },
    popularity: 27,
    name: "Честер Plus",
    price: 30000,
    countString: 4,
    setNumber: "SO135646",
  },
  {
    id: 9,
    image: guitar5,
    raiting: 4,
    type: {
      name: "acustic",
      value: "Акустическая гитара",
      image: acustic,
    },
    popularity: 3,
    name: "Виолана 300",
    price: 1700,
    countString: 7,
    setNumber: "VO154751",
  },
  {
    id: 10,
    image: guitar6,
    raiting: 4,
    type: {
      name: "electro",
      value: "Электрогитара",
      image: electro,
    },
    popularity: 20,
    name: "СURT Clasic",
    price: 23000,
    countString: 4,
    setNumber: "TK244556",
  },
  {
    id: 11,
    image: guitar1,
    raiting: 4,
    type: {
      name: "electro",
      value: "Электрогитара",
      image: electro,
    },
    popularity: 19,
    name: "СURT Z250",
    price: 18700,
    countString: 4,
    setNumber: "TK134663",
  },
  {
    id: 12,
    image: guitar2,
    raiting: 4,
    type: {
      name: "electro",
      value: "Электрогитара",
      image: electro,
    },
    popularity: 30,
    name: "Честер 7X",
    price: 35000,
    countString: 7,
    setNumber: "SO123212",
  },
  {
    id: 13,
    image: guitar4,
    raiting: 4,
    type: {
      name: "electro",
      value: "Электрогитара",
      image: electro,
    },
    popularity: 28,
    name: "Честер 6V",
    price: 14900,
    countString: 6,
    setNumber: "SO123234",
  },
  {
    id: 14,
    image: guitar5,
    raiting: 4,
    type: {
      name: "acustic",
      value: "Акустическая гитара",
      image: acustic,
    },
    popularity: 7,
    name: "Виолана Mix",
    price: 7600,
    countString: 6,
    setNumber: "VO519510",
  },
  {
    id: 15,
    image: guitar5,
    raiting: 4,
    type: {
      name: "acustic",
      value: "Акустическая гитара",
      image: acustic,
    },
    popularity: 19,
    name: "Виолана 250x",
    price: 6500,
    countString: 6,
    setNumber: "VO457369",
  },
  {
    id: 16,
    image: guitar5,
    raiting: 4,
    type: {
      name: "acustic",
      value: "Акустическая гитара",
      image: acustic,
    },
    popularity: 26,
    name: "Фабио Лайт",
    price: 12000,
    countString: 7,
    setNumber: "FB625903",
  },
  {
    id: 17,
    image: guitar5,
    raiting: 4,
    type: {
      name: "acustic",
      value: "Акустическая гитара",
      image: acustic,
    },
    popularity: 31,
    name: "Фабио L100",
    price: 9900,
    countString: 7,
    setNumber: "FB576948",
  },
  {
    id: 18,
    image: guitar5,
    raiting: 4,
    type: {
      name: "acustic",
      value: "Акустическая гитара",
      image: acustic,
    },
    popularity: 28,
    name: "Liana Z200",
    price: 8900,
    countString: 12,
    setNumber: "LU012032",
  },
  {
    id: 19,
    image: guitar5,
    raiting: 4,
    type: {
      name: "acustic",
      value: "Акустическая гитара",
      image: acustic,
    },
    popularity: 34,
    name: "Liana Z100",
    price: 10500,
    countString: 12,
    setNumber: "LU546853",
  },
  {
    id: 20,
    image: guitar5,
    raiting: 4,
    type: {
      name: "acustic",
      value: "Акустическая гитара",
      image: acustic,
    },
    popularity: 9,
    name: "Liana Z300",
    price: 13300,
    countString: 6,
    setNumber: "LU458283",
  },
  {
    id: 21,
    image: guitar3,
    raiting: 4.5,
    type: {
      name: "ukulele",
      value: "Укулеле",
      image: ukulele,
    },
    popularity: 37,
    name: "Roman RX",
    price: 4800,
    countString: 4,
    setNumber: "RO324341",
  },
  {
    id: 22,
    image: guitar3,
    raiting: 4.5,
    type: {
      name: "ukulele",
      value: "Укулеле",
      image: ukulele,
    },
    popularity: 5,
    name: "Roman TX",
    price: 1900,
    countString: 4,
    setNumber: "RO214235",
  },
  {
    id: 23,
    image: guitar3,
    raiting: 4.5,
    type: {
      name: "ukulele",
      value: "Укулеле",
      image: ukulele,
    },
    popularity: 23,
    name: "Dania U100",
    price: 2500,
    countString: 4,
    setNumber: "DI132414",
  },
  {
    id: 24,
    image: guitar3,
    raiting: 4.5,
    type: {
      name: "ukulele",
      value: "Укулеле",
      image: ukulele,
    },
    popularity: 3,
    name: "Dania WR",
    price: 3800,
    countString: 4,
    setNumber: "DI934754",
  },
  {
    id: 25,
    image: guitar3,
    raiting: 4.5,
    type: {
      name: "ukulele",
      value: "Укулеле",
      image: ukulele,
    },
    popularity: 10,
    name: "Dania LE",
    price: 4100,
    countString: 4,
    setNumber: "DI034292",
  },
  {
    id: 26,
    image: guitar3,
    raiting: 4.5,
    type: {
      name: "ukulele",
      value: "Укулеле",
      image: ukulele,
    },
    popularity: 14,
    name: "Mirana V10",
    price: 2700,
    countString: 4,
    setNumber: "MI193214",
  },
  {
    id: 27,
    image: guitar3,
    raiting: 4.5,
    type: {
      name: "ukulele",
      value: "Укулеле",
      image: ukulele,
    },
    popularity: 29,
    name: "Виолана Mini",
    price: 6700,
    countString: 4,
    setNumber: "VO043244",
  },
];
